services:
  job-scraper:
    image: ghcr.io/jnahumphreys/job-scraper:latest
    container_name: job-scraper
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  default:
    driver: bridge
